import tempfile
from pathlib import Path

from adwe.services.git_branch import create_branch
from adwe.services.git_commit import commit_changes
from adwe.services.github_pr import create_pull_request
from adwe.services.patch_apply import apply_patch
from adwe.services.repository_clone import clone_repository
from adwe.services.test_runner import run_tests
from adwe.services.errors import PatchApplyWorkflowError, TestExecutionError


def apply_patch_workflow(
    repository_url: str,
    branch_name: str,
    diff: str,
    commit_message: str,
    test_command: list[str] | None = None,
    dry_run: bool = False,
    open_pr: bool = False,
    pr_title: str | None = None,
    pr_body: str | None = None,
) -> dict:
    with tempfile.TemporaryDirectory() as tmpdir:
        repo_path = Path(tmpdir) / "repo"

        clone_repository(repository_url, repo_path)
        create_branch(repo_path, branch_name)
        apply_patch(repo_path, diff)

        test_result = None
        if test_command:
            test_result = run_tests(repo_path, test_command)

            if not test_result["passed"]:
                raise TestExecutionError(
                    f"Tests failed with exit code {test_result['exit_code']}"
                )

        if dry_run:
            return {
                "branch_name": branch_name,
                "commit_sha": None,
                "status": "validated",
                "test_result": test_result,
            }

        commit_sha = commit_changes(repo_path, commit_message)

        pull_request = None
        if open_pr:
            pull_request = create_pull_request(
                repository_url=repository_url,
                branch_name=branch_name,
                title=pr_title or commit_message,
                body=pr_body or "Generated by ADWE.",
            )

        return {
            "branch_name": branch_name,
            "commit_sha": commit_sha,
            "status": "committed",
            "test_result": test_result,
            "pull_request": pull_request,
        }
