"""add workflow timestamps

Revision ID: 1a32f5cedd2f
Revises: e6578c1b84e0
Create Date: 2026-06-06 00:44:24.168846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a32f5cedd2f'
down_revision: Union[str, Sequence[str], None] = 'e6578c1b84e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('workflows', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'completed_at')
    op.drop_column('workflows', 'started_at')
    # ### end Alembic commands ###
