"""add patch preview metadata

Revision ID: 1f818d64a372
Revises: b9e70b9b5ab8
Create Date: 2026-06-10 01:53:14.677189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f818d64a372'
down_revision: Union[str, Sequence[str], None] = 'b9e70b9b5ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patches', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('patches', sa.Column('files_changed', sa.JSON(), nullable=True))
    op.add_column('patches', sa.Column('reasoning', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patches', 'reasoning')
    op.drop_column('patches', 'files_changed')
    op.drop_column('patches', 'summary')
    # ### end Alembic commands ###
