"""add patch push requested flag

Revision ID: 32e5eafea712
Revises: ed806784e8ab
Create Date: 2026-06-06 14:06:12.352585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e5eafea712'
down_revision: Union[str, Sequence[str], None] = 'ed806784e8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patches",
        sa.Column(
             "push_requested",
             sa.Boolean(),
             nullable=False,
             server_default=sa.false(),
        ),
     )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patches', 'push_requested')
    # ### end Alembic commands ###
