"""add code modification to workflows

Revision ID: 690e2cbea360
Revises: 9f9e0710fb75
Create Date: 2026-06-05 18:23:21.166706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690e2cbea360'
down_revision: Union[str, Sequence[str], None] = '9f9e0710fb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('code_modification', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'code_modification')
    # ### end Alembic commands ###
