"""add implementation plan to workflows

Revision ID: 8029ad3f659b
Revises: cd6280ac3c94
Create Date: 2026-06-05 17:46:24.293648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8029ad3f659b'
down_revision: Union[str, Sequence[str], None] = 'cd6280ac3c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('implementation_plan', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'implementation_plan')
    # ### end Alembic commands ###
