"""add workflow retry tracking

Revision ID: b380c027fe4a
Revises: 1a32f5cedd2f
Create Date: 2026-06-06 01:25:49.563674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b380c027fe4a'
down_revision: Union[str, Sequence[str], None] = '1a32f5cedd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "workflows",
        sa.Column(
            "retry_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "workflows",
        sa.Column(
            "last_error",
            sa.String(),
            nullable=True,
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'last_error')
    op.drop_column('workflows', 'retry_count')
    # ### end Alembic commands ###
