"""add patch priority metadata

Revision ID: b4741e3f30d9
Revises: 1f818d64a372
Create Date: 2026-06-10 16:06:05.553692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4741e3f30d9'
down_revision: Union[str, Sequence[str], None] = '1f818d64a372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patches', sa.Column('priority_score', sa.Integer(), nullable=True))
    op.add_column('patches', sa.Column('priority_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patches', 'priority_reason')
    op.drop_column('patches', 'priority_score')
    # ### end Alembic commands ###
