"""add patch pr request fields

Revision ID: b9e70b9b5ab8
Revises: 32e5eafea712
Create Date: 2026-06-06 14:51:27.900410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e70b9b5ab8'
down_revision: Union[str, Sequence[str], None] = '32e5eafea712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "patches",
        sa.Column(
            "open_pr_requested",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "patches",
        sa.Column("pr_title", sa.String(), nullable=True),
    )

    op.add_column(
        "patches",
        sa.Column("pr_body", sa.String(), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patches', 'pr_body')
    op.drop_column('patches', 'pr_title')
    op.drop_column('patches', 'open_pr_requested')
    # ### end Alembic commands ###
