"""add repository analysis to workflows

Revision ID: cd6280ac3c94
Revises: 6ccfff64fa2e
Create Date: 2026-06-05 17:36:50.476046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6280ac3c94'
down_revision: Union[str, Sequence[str], None] = '6ccfff64fa2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('repository_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'repository_analysis')
    # ### end Alembic commands ###
