"""add queue job id

Revision ID: e6578c1b84e0
Revises: 364717354b5d
Create Date: 2026-06-06 00:15:35.773822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6578c1b84e0'
down_revision: Union[str, Sequence[str], None] = '364717354b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('queue_job_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'queue_job_id')
    # ### end Alembic commands ###
