"""add workflow pull request link

Revision ID: ea3d8f2d20c9
Revises: 8dd7ceca045a
Create Date: 2026-06-06 02:43:37.553364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3d8f2d20c9'
down_revision: Union[str, Sequence[str], None] = '8dd7ceca045a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('pull_request_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'pull_request_id')
    # ### end Alembic commands ###
