from adwe.models.pull_request_schema import PullRequestCreate


def test_pull_request_create_accepts_workflow_id():
    payload = PullRequestCreate(
        repository_url="https://github.com/pallets/flask",
        branch_name="adwe/test",
        title="Test PR",
        body="Generated by ADWE.",
        workflow_id="workflow-123",
    )

    assert payload.workflow_id == "workflow-123"
